# This is an example how to configure the copy command to copy snapshots from one repository to another
# The targets of the copy command cannot be specified on the command line, but must be in a config file like this.
# If the config file is named "copy_example.toml", run "rustic -P copy_example copy" to copy all snapshots.
# See "rustic copy --help" for options how to select or filter snapshots to copy.

# [repository] specified the source repository
[backend]
repository = "/tmp/repo"

# [repository] specified the source repository
[repository]
password = "test"

# you can specify multiple copy targets
[[copy]]
# First copy target
[copy.options]
# Optional, but one of the three password options must be set
# either on CLI, in the config file or in the environment variables
password = "test"
no-cache = true

[copy.backend]
repository = "/tmp/repo2"

[[copy]]
# Second copy target
[copy.options]
password-file = "/root/key-rustic-ovh"
cache-dir = "/var/lib/cache/rustic" # explicitly specify cache dir for remote repository

[copy.backend]
repository = "rclone|ovh:backup"
repo-hot = "rclone|ovh:backup-hot"
